sudo: false
language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
env:
  global:
  - secure: tp8kSmRTiL58XXVK5w0Cd6rvpwiAlr/caVoe5Uye8edW1x32G7E5kVh5qb2n8Gd58JtYLZngwRWe5v9SJ+dZZvv5jLXgNGG2V8Z9+hVRd6hoW90HULYNxTkV3JF6VGx++UI7SozWL6fhNi0dAYPsK9CHF+i+GIfP7rrNf+5MNiVoTtyYC5PbG+OOtN+nHztuUnHCyv6Cr9DdY722s80uAfs3UNjJi8T85kr25+lTaqcTlF1cSkpKKKb2rUOBx8iJLAc/apCYQvC/88vhbSyGknXhAMssB4TvOuGawB2Mh07RwzJ0t61JRyaBlL3KysAoWakCcSo/mWR9zPTWrcqdTdSEAOGTTzP6fMDCl44NcAD7thzJhg1qCMtyKUt6OYn667d0JkqAMBV2GF2hTJPJLJuIhALkcog+N4CnFdG7hfehAzt/iWs8v7EFFbuHgTWrMF/ERpElEaJVPz4lbXYv5P0OtKbuA3gJXF5GByHusYRoJeMWm7HPUpdRdjDZ5H1m+Qv3j6UakieUX8tK7Szjt3gBUubdrQEXwjETVoB5aFYNb8gY6UUi35hTAWK7gPnL+Lv4EcvWQJW7X6EUFnWV6J4oTfPIgbPy9QeYV+3IFwWfw6cwKdvBkkEfOgw7AALnmDihbdhSZ+vWpHTq+m6G9JE6D5qjb+Z/bkYKhROciHc=
  - secure: pBhhGvUZDKaSN3P2WhokIarmMO1eGJYU9fPHM4cR4wTYvRxQW7C4Fimrtx+Vm+wzK0lw5YsHXECVntEri7dUsO0WKvXJGya4SKvo6SQQabHgYEAm8mz5rW9lx6YxIiTR+5FY0T5C2XHxJmUi1LJJAY/6oQHgJZQOZ97DWUDhPtqUEt1y3TBgS2ZmLHsL7d5TJjwVxQh0ep7G4LLgtC5Vl4q3BgkvgXIBEg6vh5RpcnpH8j8I13RXzhAOmOci9SMn4aolvP7ChYBB88tbj0rZE2c6nwOuyCS5Zn6JxZNWPLKSnCT8UXw/YjR2oDVzqoKji1D4nplptsEpZ6GUt8SsjrCI+dxW2jznkPdbqwuWW718VeyVp655WtGf6Wp+PkL4lH0vYdordG5/6TPTHW9jeZ1iQiakloZ8ZZh7SvXoSq/8AFf0h+VkZ1iiwCJq8tOPESzeHjmio8bfBgur6etLZnv/RsUE1/2g0iKzHAFOQ4aGSmEEgy++aoSE0XzS1U8O1gaQW0WXv8Pbtx6YtWQtzyQ9g6OIOaiRYgjGTMhv+5lhHpl0qA1knyurTqOdiQaU+3aQQUlfDIQBBJPMJICxqDNPdR/Y7tFwwPaeoYiEoMZTPWk0IXbeBZXyR45FTfFvgtouRENDZA3HJqHpi/zq+iU0/bsjEnjnu0OtdfbVybw=
