language: rust
script:
  - cargo test -- --test-threads=1
jobs:
  include:
    - stage: rust-stable
      rust: stable
    - stage: rust-beta
      rust: beta
    - stage: rust-nightly
      rust: nightly
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
