sudo: false
language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
env:
  global:
  - secure: UGLSlIVQ3KIaKghmD6oyjq/ES/d3ZTS0CHvFnrRMF0X1VR8GAR+gWGYCaRU4+189VtHhttQua14tpDLnX+EDIXxvaHCkjJNisK1WLwZiFJN5SaJ+hw2kj/jZvqS3FbEVMa4xpql7kYnZ7KV+Z8XFLAtnudi0qZgIO/MqH1mRm82DI+hyCmPJqJMEZKX1KbBJKllFRgTiYzwkQ/qcwKDQelFk3evu/EODppXGQ7d3YiQcc2Ju+9S7Fjl0i/FU9EgQHXQk4mf1UnOO/88rd8/h2ueNb465wWheXz23FW5n716uAedNlPvktvDRtRi7skWU0eendDI3q8u6PovG/DpFctK7V1VQtgyzCjeFNEJUjh8/lKiyecG9x+uyhUTmSejTkEd0M6xL66/VK/z+yPjm4SYOlTENFZAT+DzkC7gIFfQrBkh0mkEGrsE71W8SWLOdRmOA5/cyEtgPu5lYGUTrZM3gg3PdWGOHnShLoSjf1W5CghJDUzCTSRqNoXtylQ74J+fSG48nI052jCmizq9hkYdMKH0Qhn2ySfAwpqtMJf39vtKqhGvXErX2DMR2eerGni0nUKTBXzKzEHayQE16KIYDUyNVDXQWo9Jhp0eUg9Xwp1b7RdHwP26IeNJ+moNdvLxsbFJR7jHVqrZNCBYls6WBZvnnjvjaEiW5NlpH9mI=
  - secure: GnyxxNR5LfPGp7DHYeh6ANJoYlf6J9b0MNhxx3NKLpogBGsbZKijPjjlV8DJ0jMzBLGLBITe1FIdI6Fi/R83uWNQvc5VMSW929cdWZxZME9c9x+qqg98MCtvVUwAT8+DVU0dmTELpkKX6h68Rz8rmekaRkSpIOcQvmAcxndt6Q8sEI4DNvmG9q1VVE02HYz3WFaIrEZ1x8xAId7v4N99S94xD/c1PLje6jk+7f24CKXe9pUfpSHO/ynwv7U2/BvjAhJFCs3uBTmdSquWR5hgZ818MDocE34+eYOFV2AXJ//A/3HhSgKKUPr3nEL1atMa2YJF6h9DYxZ7eSYlxGCxirR8W6zt54zp7jr7lVHsDiPHckVWYj3pbcUm0jyOTMD3AODC2SHM7f7yO26CYNiGw4N/rCUz1vYAbzskdOUN9MRd1pmDk/HmPnPCF7jfGRXplVHiE31Ix0/4t2lP1GBXq6QpLBcNkG2c5q963oFEjDcpFQ3THcHeMZybVZ2imi66uh2B0PVCVUaFhttmuAz4sj/DMd5/PNbev12Jv3JfOSkZuOu5cLLElrtDEw/r6KVYsdq3eE9efKho0NN+DHwGJaHWOBhNLfXCD1wJFYEOv6Iz5wNcq1JwVJLAflUUaoYkCc/nsXcIAK1J2Sm9kTC52URk8D2nu9tmYw1v2uMrOhc=
