sudo: false
language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
env:
  global:
  - secure: B4BS4nXft8RXtALFqUOtPsP2Dfj3ufInqjUt16OX+rJ81vPCS5PZsp5BPcStYlfFlM4rPyIkki8cRzAYWpo5Zrz98UmK3VUU5F9MxszeNSvrmiYVFi9+0PoPR6243syFva6ZtbLxoxwhQHp7q9so7KSyfidOxsSlWcvxGKmn136bc+7FQ2W2W57t7jp9MZjp723ZNr3jDpU5kvn2KKeTzUpXpzGLYQYFVEgn7IFhtd6BbbchgOr12X/ruzwz2AnJ1debEwQ3sT6xjso2PTjWU/KalOE3X2l3mSLeFQoPod5m/IdEqjLBaYFOhAPmycLZXDfdLcc+hNIFMF8VIplYw7lkp3R3COoAZNZeomaxFqS3OnjCtimhCkTI3JurcDBo6ksSIV7kuKxF4iCe7pYqhLDG5kFqRYfUk8xp8Bm9awnEc4uUkF1Vnn81MYN8Nu6Z/MEGa/FMnR+1jX67nOJj9xc02HTGdaTokOcpp79pJmDmaGipyZro4R8qoibTEjkQlJDKClwGCEybm8uagcGzWE2CgsQGSSEtIwBvWQp5kbcwWaakKnuzrHkzr/MKqU0j95Ax2+Y8OBGoldY64/NIDym9w8AZRc7eT810vI5zTmTXAgqESR/x315w5klnzqg/2xwRUach4KpssmRPRP2ERDxP5sR//Q4cNj3bBHTQjlg=
  - secure: MRn/KHbhw9AhpvDH/uNwYDhkmMYSre/YDMorVfU7OEqm4Zm1bP3YbDV53C8UGdOubwXY1sLUgOGzXEhI8U3axAcchuBKh7uVWBwjAZDAzRHA9UzWcf7+UKxg0uFBBOD5wBMpB0D7U8Ws5K6VDI7tWvtt3gUVXdG6e+648N6VHqCw3gsVJnYc5uF6J6U4fyZZzyRqWtE1q6E5AYredF00g6s3ro/U6pNH1ZsJ+SXLAM/Q18GeOVdcon9GrOaa7asI7otkw4No4FsjXnsa2yBa8WHwvU/Qxee7fnGyXEUCpljZOR/CsV/fgREow9Qqev9964lyFk8LM1BZaOPqODulBy+rRC4eaGtUfz12mnoKeVdDJkl/Zkmn37DUBzcjchFjp2UQF3lWhFx4Ulc6weiHGejFt1bH7ncVZhGoxaX79Bm6O7rcAMNI7SjywLC1nyfXPP0aWhpgnQRYec2GKZWowhOqCG/X6U4L4DHbL4gnonsJky8fcSjaMzjvOkzehGu6hz2fWxQEmDFmwCIX4+UNfPwLkhgSK8B5s+kV6aT43+LDiaPtUIqKkH+oXFwvq/pBa5AzW1AaW/8ue+8XlTvo3slAJLUm5dSpgSatvG5W7x5EpAg4Y4YjnFQ3PWyr4cOxOSMSzex7X4DnkA2QUD4xy/s45LMXq7C9yZK73R2krzs=
